// src/app/profile-image/profile-image.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-profile-image',
  imports: [NgOptimizedImage],
  templateUrl: './profile-image.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProfileImageComponent {}

<div class="relative m-0">
  <div class="ml-2 md:ml-12 mt-2 md:mt-12 block after:absolute after:left-16 after:top-4 after:border-cyan-500 after:border-4 after:rounded-[10px] after:w-[200px] after:h-[200px] w-[200px] h-[200px]">
    <img
      ngSrc="assets/images/profile_photo.jpg"
      width="200"
      height="200"
      alt="Melanga Dissanayake"
      class="relative w-[200px] h-[200px] rounded-[10px] z-10"
      priority
    />
  </div>
</div>

// src/containers/AboutMeSection/ProfileImage.jsx
import { motion } from "framer-motion";
import React from "react";
import tw from "twin.macro";
import profilePhoto from "../../images/profile_photo.jpg";

const ImgDiv = tw(motion.div)`
    relative m-0
`;

const ImageWrapper = tw.div`
    ml-2 md:ml-12 mt-2 md:mt-12 block after:absolute after:left-16 after:top-4 after:border-cyan-500
    after:border-4 after:border-radius[10px] 
    after:width[200px] after:height[200px]
    width[200px] height[200px]

`;

const ProfileImg = tw(motion.img)`
    relative
    width[200] height[200] border-radius[10px] z-10
`;

export const ProfileImage = ({ variants }) => {
  return (
    <ImgDiv variants={variants}>
      <ImageWrapper>
        <ProfileImg src={profilePhoto} variants={variants}></ProfileImg>
      </ImageWrapper>
    </ImgDiv>
  );
};
