// src/containers/AboutMeSection/AboutMeSection.jsx
import { motion } from "framer-motion";
import React from "react";
import styled from "styled-components";
import tw from "twin.macro";
import { HeaderText } from "../../components/HeaderText";
import { ProfileImage } from "./ProfileImage";
import TecSection from "./TecSection";

const AboutMeSectionContainer = styled.div`
  ${tw`
      w-full flex md:h-screen justify-center
      bg-gradient-to-r from-blue-900 to-cyan-500
    `}
`;

const ContentWrapper = tw(motion.div)`
  flex flex-col self-center lg:max-width[1000px] 2xl:max-width[1200px] sm:height[80%] h-full
  mt-12 mb-12 mx-4 sm:mr-12 sm:ml-12 bg-opacity-10 bg-purple-800 border-radius[10px] sm:p-3
`;

const SectionColumn = styled.div`
  ${tw`
      self-center flex w-full md:flex-row flex-col p-6
    `}
`;

const SectionRowLeft = styled(motion.div)`
  ${tw`
      h-full md:flex[20%] flex[40%] justify-start relative pr-8
    `}
`;

const SectionRowRight = styled(motion.div)`
  ${tw`
      height[auto] mt-12 
      flex[60%] 2xl:flex[70%] 
      justify-start border-l-4 border-solid border-l-cyan-200
    `}
`;

const DescriptionWrapper = tw.div`
    justify-start pt-12 pl-6 pb-8 
`;

const Description = tw(motion.p)`
  text-base sm:text-lg md:text-lg text-white
`;

export default function AboutMeSection() {
  const animationProps = {
    hidden: { opacity: 0, y: -20 },
    show: {
      y: 0,
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.2,
        duration: 0.7,
      },
    },
  };

  return (
    <AboutMeSectionContainer id={"About"}>
      <ContentWrapper
        variants={animationProps}
        initial="hidden"
        whileInView={"show"}
      >
        <HeaderText text={"About Me"} />
        <SectionColumn>
          <SectionRowLeft variants={animationProps}>
            <ProfileImage variants={animationProps} />
          </SectionRowLeft>
          <SectionRowRight variants={animationProps}>
            <DescriptionWrapper>
              <Description variants={animationProps}>
                I'm Melanga Dissanayake and I am currently an undergraduate at the
                Uva Wellassa University of Sri Lanka pursuing my B.Sc. (Hons)
                in Industrial Information Technology.
                <br /> <br /> Software Engineering | Machine Learning | Mobile App Development are my interesting areas of study.
              </Description>
            </DescriptionWrapper>
            <TecSection variants={animationProps} />
          </SectionRowRight>
        </SectionColumn>
      </ContentWrapper>
    </AboutMeSectionContainer>
  );
}

// src/app/about-me-section/about-me-section.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { HeaderTextComponent } from '../header-text/header-text.component';
import { ProfileImageComponent } from '../profile-image/profile-image.component';
import { TecSectionComponent } from '../tec-section/tec-section.component';
import { ScrollAnimateDirective } from '../core/scroll-animate.directive';

@Component({
  selector: 'app-about-me-section',
  imports: [HeaderTextComponent, ProfileImageComponent, TecSectionComponent, ScrollAnimateDirective],
  templateUrl: './about-me-section.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AboutMeSectionComponent {}

<section
  id="About"
  class="w-full flex md:min-h-screen justify-center bg-gradient-to-r from-blue-900 to-cyan-500"
>
  <div class="flex flex-col self-center lg:max-w-[1000px] 2xl:max-w-[1200px] sm:h-[80%] h-full mt-12 mb-12 mx-4 sm:mx-12 bg-purple-800/10 rounded-[10px] sm:p-3">
    <div appScrollAnimate animation="fade-up">
      <app-header-text text="About Me" />
    </div>
    <div class="self-center flex w-full md:flex-row flex-col p-6">
      <div
        appScrollAnimate animation="slide-left" animationDelay="200ms"
        class="h-full md:flex-[20%] flex-[40%] justify-start relative pr-8"
      >
        <app-profile-image />
      </div>
      <div class="h-auto mt-12 flex-[60%] 2xl:flex-[70%] justify-start border-l-4 border-solid border-l-cyan-200">
        <div
          appScrollAnimate animation="fade-up-slight" animationDelay="300ms"
          class="justify-start pt-12 pl-6 pb-8"
        >
          <p class="text-base sm:text-lg md:text-lg text-white">
            I'm Melanga Dissanayake and I am currently an undergraduate at the Uva Wellassa University of Sri Lanka pursuing my B.Sc. (Hons) in Industrial Information Technology.
            <br /><br />
            Software Engineering | Machine Learning | Mobile App Development are my interesting areas of study.
          </p>
        </div>
        <div appScrollAnimate animation="fade-up" animationDelay="400ms">
          <app-tec-section />
        </div>
      </div>
    </div>
  </div>
</section>
