// src/app/projects-section/projects-section.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { HeaderTextComponent } from '../header-text/header-text.component';
import { ProjectWidgetComponent } from '../project-widget/project-widget.component';
import { ScrollAnimateDirective } from '../core/scroll-animate.directive';
import { PROJECTS } from '../core/projects.data';

@Component({
  selector: 'app-projects-section',
  imports: [HeaderTextComponent, ProjectWidgetComponent, ScrollAnimateDirective],
  templateUrl: './projects-section.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProjectsSectionComponent {
  protected readonly projects = PROJECTS;
}

<section
  id="Projects"
  class="border-t-2 border-cyan-500 w-full flex bg-gradient-to-r from-blue-900 to-cyan-500 justify-center"
>
  <div class="flex flex-col self-center lg:max-w-[1000px] 2xl:max-w-[1200px] h-full mt-12 mb-12 mx-4 sm:mx-12 rounded-[10px] relative w-full gap-4 sm:gap-16">
    <div appScrollAnimate animation="fade-up">
      <app-header-text text="Projects" />
    </div>
    @for (project of projects; track project.id; let i = $index) {
      <div
        appScrollAnimate
        [animation]="i % 2 === 0 ? 'slide-left' : 'slide-right'"
        [animationDelay]="'100ms'"
      >
        <app-project-widget [project]="project" [imgLeft]="i % 2 === 0" />
      </div>
    }
  </div>
</section>

// src/containers/ProjectsSection/ProjectsSection.jsx
import React from "react";
import tw from "twin.macro";
import { HeaderText } from "../../components/HeaderText";
import { Project1Data, Project2Data, Project3Data } from "./ProjectsDetails";
import ProjectWidget from "./ProjectWidget";

const ProjectsSectionContainer = tw.div`
  border-t-2 border-cyan-500 w-full flex bg-gradient-to-r from-blue-900 to-cyan-500 justify-center
`;

const ContentWrapper = tw.div`
  flex flex-col self-center lg:max-width[1000px] 2xl:max-width[1200px] h-full
  mt-12 mb-12 mx-4 sm:mr-12 sm:ml-12 border-radius[10px] relative w-full gap-4 sm:gap-16
`;

export default function ProjectsSection() {
  return (
    <ProjectsSectionContainer id={"Projects"}>
      <ContentWrapper>
        <HeaderText text={"Projects"} />
        <ProjectWidget {...Project1Data} imgLeft={true} />
        <ProjectWidget {...Project2Data} imgLeft={false} />
        <ProjectWidget {...Project3Data} imgLeft={true} />
      </ContentWrapper>
    </ProjectsSectionContainer>
  );
}
