// src/containers/TopSection/TopSection.jsx
import React from "react";
import tw from "twin.macro";
import Typed from "typed.js";
import styled from "styled-components";
import backgroundImage from "../../images/background_image.jpeg";
import NavBar from "../../components/NavBar";
import { Link } from "react-scroll";
import { BsArrowDownCircle } from "react-icons/bs";
import { motion, useTransform, useViewportScroll } from "framer-motion";

const TopSectionContainer = styled.div`
  ${tw`
    w-full flex h-screen
`}
`;

const LandingSection = styled(motion.div)`
  ${tw`
        w-full h-screen flex flex-col justify-items-center
    `};
  background-image: url(${backgroundImage}),
    linear-gradient(to left, #6e15801d, #114264);
  background-size: cover;
  background-position: bottom 10% left;
  background-blend-mode: overlay;
`;

const InfoSection = styled(motion.div)`
  ${tw`
    absolute top[150px] left-4 sm:right-40 sm:left-auto 2xl:right-40 2xl:top[180px]
  `}
`;

const FloatingText = styled(motion.div)`
  ${tw`
    m-0 font-black text-white sm:mb-2
    font-size[60px] line-height[60px]
    sm:font-size[80px] sm:line-height[70px] 
    md:font-size[100px] md:line-height[80px] 
    lg:font-size[125px] lg:line-height[100px]
    2xl:font-size[145px] 2xl:line-height[130px]
    font-family["Ubuntu"]
    flex items-center
  `}
`;

const OutlinedTextSvg = styled.svg`
  //font: bold 100px Century "Archivo Narrow", Arial;
  ${tw`
        width[fit-content]
        sm:width[auto]
        height[70px]
        sm:height[100px]
        2xl:width[550px]
        flex
        sm:mt-1
        2xl:mt-4
    `};
  overflow: overlay;
  text {
    max-height: 100%;
    flex: 1;
    fill: none;
    stroke: white;
    stroke-width: 1px;
    stroke-linejoin: round;
    z-index: 99;
    ${tw`
      sm:transform[translateY(60px)]
      md:transform[translateY(72px)]
      lg:transform[translateY(97px)]
      2xl:transform[translateY(100px)]
      transform[translateY(50px)]
    `};
    text-shadow: 0px 0px 0px rgba(255, 255, 255, 0.5);
  }
`;

const DescriptionText = styled(motion.div)`
  ${tw`
    text-base md:text-lg text-white text-opacity-80 mt-2 sm:mt-10 2xl:mt-20 max-w-lg 2xl:max-w-xl mr-4 sm:ml-1.5
  `}
`;

const ViewMoreButton = styled(motion.button)`
  ${tw`
    absolute bottom-6 self-center text-white text-4xl
  `}
`;

const TopSection = ({ isTablet }) => {
  // Create reference to store the DOM element containing the animation
	const el = React.useRef(null);
  // Create reference to store the Typed instance itself
	const typed = React.useRef(null);

  React.useEffect(() => {
    const options = {
    	strings: [
        'Developer',
        'Enthusiast',
        'Programmer',
      ],
      typeSpeed: 50,
      backSpeed: 50,
      loop: true,
    };
    
    // elRef refers to the <span> rendered below
    typed.current = new Typed(el.current, options);
    
    return () => {
      // Make sure to destroy Typed instance during cleanup
      // to prevent memory leaks
      typed.current.destroy();
    }
  }, [])

  const animationProps = {
    hidden: { opacity: 0, y: -20 },
    show: {
      y: 0,
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.5,
        duration: 0.7,
      },
    },
  };

  const { scrollY } = useViewportScroll();
  const factor = isTablet ? 0.3 : -0.2;
  const yBody = useTransform(scrollY, (value) => value * factor);
  const yNav = useTransform(scrollY, (value) => value * 1);

  return (
    <TopSectionContainer>
      <LandingSection variants={animationProps} animate="show" initial="hidden">
        <NavBar variants={animationProps} style={{ y: yNav }} />
        <InfoSection style={{ y: yBody }}>
          <FloatingText variants={animationProps}>Hi,</FloatingText>
          <FloatingText
            variants={animationProps}
            style={{ display: "inline-flex" }}
          >
            I'm&nbsp;
          </FloatingText>
          <FloatingText
            variants={animationProps}
            animate={{ color: ["#1990be", "#19bea2", "#1990be"] }}
            transition={{
              ease: "easeOut",
              duration: 5,
              repeat: Infinity,
            }}
            style={{ display: "inline-flex" }}
          >
            Melanga
          </FloatingText>
          <FloatingText variants={animationProps}>
            <OutlinedTextSvg>
              <text ref={el}></text>
            </OutlinedTextSvg>
          </FloatingText>
          <DescriptionText variants={animationProps}>
            I'm Melanga Dissanayake, an undergraduate at the Uva
            Wellassa University of Sri Lanka pursuing my B.Sc. (Hons) in
            Industrial Information Technology.
          </DescriptionText>
        </InfoSection>
        <ViewMoreButton
          whileHover={{
            scale: 1.2,
            color: "#19bea2",
            transition: { duration: 0.3 },
          }}
          whileTap={{ scale: 0.9 }}
          variants={animationProps}
        >
          <Link to="About" smooth={"easeInOutQuad"} duration={1000}>
            <BsArrowDownCircle />
          </Link>
        </ViewMoreButton>
      </LandingSection>
    </TopSectionContainer>
  );
};

export default TopSection;

// src/app/top-section/top-section.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  inject,
  viewChild,
  AfterViewInit,
  OnDestroy,
  ElementRef,
} from '@angular/core';
import Typed from 'typed.js';
import { ResponsiveService } from '../core/responsive.service';
import { NavbarComponent } from '../navbar/navbar.component';
import { ScrollToDirective } from '../core/scroll-to.directive';
import { ScrollAnimateDirective } from '../core/scroll-animate.directive';

@Component({
  selector: 'app-top-section',
  imports: [NavbarComponent, ScrollToDirective, ScrollAnimateDirective],
  templateUrl: './top-section.component.html',
  styleUrl: './top-section.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TopSectionComponent implements AfterViewInit, OnDestroy {
  private readonly responsive = inject(ResponsiveService);
  private typedInstance: Typed | null = null;

  readonly typedTarget = viewChild<ElementRef<HTMLSpanElement>>('typedTarget');
  protected readonly isTablet = this.responsive.isTablet;

  ngAfterViewInit(): void {
    this.initTypedAnimation();
  }

  ngOnDestroy(): void {
    this.typedInstance?.destroy();
  }

  private initTypedAnimation(): void {
    const el = this.typedTarget()?.nativeElement;
    if (el) {
      this.typedInstance = new Typed(el, {
        strings: ['Developer', 'Enthusiast', 'Programmer'],
        typeSpeed: 50,
        backSpeed: 50,
        loop: true,
      });
    }
  }
}

<div class="w-full flex h-screen">
  <section
    class="top-section-landing w-full h-screen flex flex-col justify-items-center bg-cover bg-[bottom_10%_left] bg-no-repeat"
    style="background-image: linear-gradient(to left, #6e15801d, #114264), url('assets/images/background_image.jpeg'); background-blend-mode: overlay;"
  >
    <app-navbar />
    <div class="absolute top-[150px] left-4 sm:right-40 sm:left-auto 2xl:right-40 2xl:top-[180px]">
      <p
        appScrollAnimate animation="fade-up-slight" animationDelay="200ms"
        class="m-0 font-black text-white sm:mb-2 text-[60px] leading-[60px] sm:text-[80px] sm:leading-[70px] md:text-[100px] md:leading-[80px] lg:text-[125px] lg:leading-[100px] 2xl:text-[145px] 2xl:leading-[130px] font-['Ubuntu'] flex items-center"
      >
        Hi,
      </p>
      <p
        appScrollAnimate animation="fade-up-slight" animationDelay="400ms"
        class="m-0 font-black text-white sm:mb-2 text-[60px] leading-[60px] sm:text-[80px] sm:leading-[70px] md:text-[100px] md:leading-[80px] lg:text-[125px] lg:leading-[100px] 2xl:text-[145px] 2xl:leading-[130px] font-['Ubuntu'] flex items-center inline-flex"
      >
        I'm&nbsp;
      </p>
      <p
        appScrollAnimate animation="fade-up-slight" animationDelay="600ms"
        class="m-0 font-black sm:mb-2 text-[60px] leading-[60px] sm:text-[80px] sm:leading-[70px] md:text-[100px] md:leading-[80px] lg:text-[125px] lg:leading-[100px] 2xl:text-[145px] 2xl:leading-[130px] font-['Ubuntu'] flex items-center inline-flex text-cyan-400"
      >
        Melanga
      </p>
      <p
        appScrollAnimate animation="fade-up-slight" animationDelay="800ms"
        class="m-0 font-black text-white sm:mb-2 text-[60px] leading-[60px] sm:text-[80px] sm:leading-[70px] md:text-[100px] md:leading-[80px] lg:text-[125px] lg:leading-[100px] 2xl:text-[145px] 2xl:leading-[130px] font-['Ubuntu'] flex items-center"
      >
        <span
          #typedTarget
          class="typed-outline inline-block w-fit sm:w-auto min-h-[70px] sm:min-h-[100px] sm:mt-1 2xl:mt-4"
        ></span>
      </p>
      <p
        appScrollAnimate animation="fade-in" animationDelay="1000ms"
        class="text-base md:text-lg text-white/80 mt-2 sm:mt-10 2xl:mt-20 max-w-lg 2xl:max-w-xl mr-4 sm:ml-1.5"
      >
        I'm Melanga Dissanayake, an undergraduate at the Uva Wellassa University of Sri Lanka pursuing my B.Sc. (Hons) in Industrial Information Technology.
      </p>
    </div>
    <a
      href="#About"
      anchorId="About"
      appScrollTo
      appScrollAnimate animation="fade-in" animationDelay="1200ms"
      class="absolute bottom-6 self-center text-white text-4xl hover:scale-110 hover:text-cyan-400 transition-all duration-300 active:scale-90"
      aria-label="Scroll to About"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12" fill="currentColor" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
      </svg>
    </a>
  </section>
</div>
